### ISSUE TITLE
Ability to Capture Zones with Jets

### ISSUE THREAD

**Issue by Igneous01** [KaukausInsurgency/kaukasusinsurgency-dcs#163]
There should be a way for jets to capture zones either by calling convoy, or combined arms.

Or if the capture point is neutral, spawn blue and red groups to engage on the zone.

**Comment by Igneous01** [comment]
Couple of options for this one:

a) call ground convoy - provide ability to call a ground convoy to capture the zone,
b) airdrop - spawn a cargo plane like C130 to fly over capture point, if it crosses waypoint successfully, spawn infantry on the ground 20 seconds later to simulate paradrop. If it dies before crossing the waypoint no paradrop happens. This would be an awesome idea to implement as a sidemission, and gives cap opportunity to escort the paradrop and intercept any fighters.

**Comment by Igneous01** [comment]
# Changes needed to support airdrop:

1. Add a configurable zone or list of zones where an airdrop plane would be spawned (mid air), or provide the option of how the plane would spawn in (on ramp, ramp hot, in air, etc).

2. Create F10 Menu for all players to call airdrop - this would either need to:
  A) show all neutral capture points only, and routinely update the menu with a scheduler function
  B) show all capture points

3. If multiple users call in an airdrop at the same time, only the first request should happen (so need some sort of global variable that indicates a drop was called).

4. There should be a configurable cooling off time before another airdrop can be called

5. There should be a configurable setting for specifying the number of airdrops that can be called in at one time. But multiple airdrops cannot be called on the same capture point.

6. When the plane spawns in, create a flight route towards the CP zone (for now just straight b-line to the target, writing pathing code so that it takes a path avoiding enemy zones along the way is far too difficult to implement). Create a second waypoint back to the spawn origin. Need to figure out the cruising altitude (perhaps make this a configurable setting?)

7. Add a scheduler function that checks if the air unit is inside the zone (or within 10km of the center). If it is, message to all coalition that the airdrop is in progress, then run another scheduled function after x amount of seconds where infantry would be spawned inside the zone. (Infantry should be a group template provided in config, paradrop delay should also be configurable).

8. Add logic so that if the airplane dies before reaching the inzone check, no airdrop occurs, and the routine is aborted.


## Configuration Options needed:

**Airdrop.Config.SpawnZones** = { "Zone1", "Zone2", ... }
**Airdrop.Config.PlaneTemplate** = "C130-Group-Template"
**Airdrop.Config.PlaneSpawnIn** = "Ramp" or "MidAir" or "Ramp Hot"
**Airdrop.Config.Cooldown** = 1800  -- time it takes for airdrop to be available again in seconds
**Airdrop.Config.MaxAirdropsPerCooldown** = 3 -- number of airdrops that can be called within cooldown period
**Airdrop.Config.MaxAirdropsPerSession** = 10 -- maximum number of times players can call an airdrop in a single session (until next server restart)
**Airdrop.Config.PlaneCruisingSpeed** = 600 -- the cruising speed towards the waypoint in km/h
**Airdrop.Config.PlaneCruisingAltitude** = 2000 -- the cruising altitude towards the waypoint in meters
**Airdrop.Config.AirdropDistance** = 10000 -- the distance plane needs to be from center of zone to initiate airdrop
**Airdrop.Config.ParachuteTime** = 120 -- the time in seconds from initial drop message to time the infantry actually spawn in the zone
**Airdrop.Config.AirborneInfantryTemplate** = {"MyInfantryTemplate", "MyInfantryTemplate2"} -- the group templates to spawn into the zone

### future configuration ideas:

1. Ability to define multiple airdrop types (ie. humvee drop, infantry drop, supply drop)
2. Ability to define separate parameters for each type (ie max airdrops, cooldown period, etc)

### Caveats

1. There is little we can do to prevent abuse. Players can just spam the airdrop commands on as many areas as possible, which can interfere or cause a negative experience for players trying to coordinate together on a certain zone.

2. Probably would not be saved in savefile on restart. If the drop does not happen because of restart, on reload the plane would be gone.

**Comment by Igneous01** [comment]
Also need to consider:

adding a score event when an airdrop is called by a player. (KI_EVENT_AIRDROP_CALLED) which produces arguments (event.initiator - unit that requested the airdrop, event.cargo - the type of airdrop called). Can add this to player overall stats (ie. number of airdrops called).

Ability for the enemy insurgent commander to spawn interceptors to engage the supply drop vehicle (part of AICOM_AIR module). Should be a random chance that is configurable (ie. AICOM.Config.AirInterceptAirdropChance = 30%)

This would require that the supply drop is a far enough distance away (at least 10 - 15 minutes travel time) so that the AI Commander has enough time to dispatch an interceptor squad to engage. Anything shorter is probably not going to work.

**Comment by Igneous01** [comment]
# Changed needed to support calling in supply convoy

1. Can use supplier depot as the spawn origin point for a combat convoy. The closest supplier depot to the actual capture point would be the one used. Logistic convoys work like this already so little effort here.

2. Spawn the group templates (configurable) and assign them an 'On Road' waypoint to the capture point zone.

3. Group templates should be mixed / allow random choice - either it's 1 group template per combat convoy, or multiple sets of groups per combat convoy. 

4. Create F10 Menu for all players to call combat convoy - this would either need to:
A) show all neutral capture points only, and routinely update the menu with a scheduler function
B) show all capture points

5. If multiple users call in a combat convoy at the same time, only the first request should happen (so need some sort of global variable that indicates when a convoy was called).

6. There should be a configurable cooling off time before another combat convoy can be called

7. There should be a configurable setting for specifying the number of convoys that can be called in at one time. But multiple convoys cannot be called on the same capture point.

8. Save the combat convoy and it's current waypoint to the save file so that on reload the group reinitiates the waypoint again. Already do this with logistic convoys so logic is already in place.

ie. 

Mixed Combat Groups: 
{ 
  CombatGroupA = { "ThisTemplate", "ThatTemplate" }, 
  CombatGroupB = {"This Template", "Another Template"}
} 
or 
{ "ThisTemplate", "ThatTemplate", "Another Template"}


## Configuration Options needed:

**CombatConvoy.Config.GroupTemplates** = {} -- group templates to use
**CombatConvoy.Config.Cooldown** = 1800 -- time it takes for convoy to be available again in seconds
**CombatConvoy.Config.MaxConvoysPerCooldown** = 3 -- number of convoys that can be called within cooldown period
**CombatConvoy.Config.MaxConvoysPerSession** = 10 -- maximum number of times players can call a convoy in a single session (until next server restart)

The work required here is significantly less than in the airdrop one. Player feedback on these options would be much appreciated.

### Caveats

1. This has the potential disadvantage that if the closest supplier depot to a capture point is ~50 km away, players could expect to wait several hours before the convoy actually arrives.

**Comment by Igneous01** [comment]
Things to consider for combat convoys

Adding a score event when a convoy is called by a player. (KI_EVENT_COMBAT_CONVOY_CALLED) which produces arguments (event.initiator - unit that requested the convoy, event.cargo - the type of convoy called). Can add this to player overall stats (ie. number of convoys called).

**Comment by thebgpikester** [comment]
Hows about, a paradrop. Once a zone is capture, a C130 spawns at the nearest frienbdly (large) airbase and use a moose route to zone at a 10k ft altitude, so that they are vulnerable to residual SAM's. Simply spawn a squad of soldiers in zone when it arrives. Mechanics and cost up to you.

The method i'm shooting for on our server is constantly spawning ground troops, but that's another matter. Requires tuning with the sizes of forces so not too much combat occurs, but essentially it makes sure stuff is always going on.

**Comment by Igneous01** [comment]
Yeah how you explained the paradrop is how I was thinking of approaching that. I think I have what I need to implement. Thanks for feedback!

**Comment by Igneous01** [comment]
Estimate - 3 to 5 days effort including testing

**Comment by thebgpikester** [comment]
Side note; Moose capture zones include air units for some reason. Not sure this would generate sensible player play though!! :)

**Comment by Igneous01** [comment]
Work got a little stalled yesterday as I was trying to get the prototype of this to work. I think i'm back on track now that I got the plane to spawn at random airbase + keep altitude.

The F10 Menu and Airdrop Config stuff is done, as well as the plane spawning and going to waypoint. All that's left is creating the cooldown / spawn ground units stuff which shouldn't take long.

**Comment by Frosties82** [comment]
Awesome! Looking forward to testing it!

**Comment by Igneous01** [comment]
Was delayed a few days because of RL / Business Trip - going back into this.

Where I last left off - everything was working (you could spawn an airdrop on any zone you wanted, the cooldown timer worked, and the config stuff worked). It would spawn the airdrop and the plane, the only issue I noticed was that when the plane was spawned at an airfield, it would take off, make a very deep turn to the right/left to the point of diving down into the ground, then never try to regain control and climb to expected altitude.

It looks like it was random as well - sometimes the plane would dolphin dive into the air and reach it's target altitude, other times the dolphin dive would crash itself into the ground.

**Comment by Igneous01** [comment]
I tested it again using a different airport and the plane did not crash... it still did this weird dolphin diving maneuver to gain altitude but it successfully reached the target zone and dropped it's payload - so I think this feature is complete, just buggy using some airfields in DCS

**Comment by Igneous01** [comment]
Completed work in branch. Last commit: 4523b6d4b3b8cb04307d6c12f5531ca992161e32

**Comment by Igneous01** [comment]
Related to AI Plane crashing on takeoff: https://github.com/FlightControl-Master/MOOSE/issues/793
