### ISSUE TITLE
Add F10 Markers On Map

### ISSUE THREAD

**Issue by Igneous01** [KaukausInsurgency/kaukasusinsurgency-dcs#165]
Based on feedback from Frosties - F10 Markers should be created on map indicating each CP and Depot.

**Comment by thebgpikester** [comment]
http://wiki.hoggit.us/view/DCS_func_markToAll

this way

**Comment by Igneous01** [comment]
thank you good sir!

**Comment by Igneous01** [comment]
Added this in, but the map is very very cluttered if you have a good amount of points on the map.

![image](https://user-images.githubusercontent.com/5571589/35480408-607e8f1e-03db-11e8-8ca5-004654207bc9.png)

Rather than force this on the server admin, making this a configurable option in the KI_Config.lua file. That way if server admins want the markers they can turn them on or off.

KI.Config.DisplayDepotMarkers = true -- whether to show markers on map for depots
KI.Config.DisplayCapturePointMarkers = true -- whether to show markers on map for capture points

**Comment by Igneous01** [comment]
Work completed in master branch

**Comment by thebgpikester** [comment]
Already? :D awesome!
