### ISSUE TITLE
MOOSE legacy version 2.0 vs current 2.3 alpha

### ISSUE THREAD

**Issue by thebgpikester** [KaukausInsurgency/kaukasusinsurgency-dcs#203]
I've come across some coding issues with the current 2.0 version lacking some functions I need to develop on.

I wonder if you could do some regression testing on 2.3 alpha with us or a heads up on which components of MOOSE are mission critical or stuck on the earlier version? Ideally I'd like it to be updated but i'm not sure on the net effect.

Will be trying myself shortly, but it's at someone else's speed so I may be slow to feedback.

**Comment by Igneous01** [comment]
I can schedule some time to do this sure - majority of classes being utilized in KI are GROUP, UNIT, COORDINATE, ZONE, SPAWN, so if these are stable in 2.3 alpha the switch should be fine. 

If you want to try now with 2.3, the mission trigger in ME needs to be updated to load the latest moose script file.

**Comment by Frosties82** [comment]
I have added the latest (to my knowledge) and will toss it on the server in a few minutes.

**Comment by Frosties82** [comment]
It seems that it is working. I dont experience any errors in the log, and Everything seems to be spawning as it should (KI related).

**Comment by Igneous01** [comment]
That is very promising - will look at updating the moose script referenced to 2.3 alpha

**Comment by thebgpikester** [comment]
I'm not sure about COORDINATE, that might have had some change, but the rest definitely not. Good news nothing obvious broke, in which case as long as we know, a change here would be beneficial to an entire community. The current version i'm interested in has fixes for menus. it's not on the public download. Look for the build date with anything 2018 in it. NOT 2.2 patch 6, but 2.3 alpha ( i have a copy with a build date of 20171222_1247 if you need)
We will continue working with 2.3 alpha and report back any issues as we notice them. No rush here, UNLESS you want to use the http://flightcontrol-master.github.io/MOOSE/Documentation/ZoneCaptureCoalition.html functions, which are pretty cool. However, all markers are broken in 2.5 due to changes there.

**Comment by Frosties82** [comment]
I am running 20171222_1247 on the server right now

**Comment by Igneous01** [comment]
Have you guys tested whether the F10 menu works for helicopters?
